import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/css/globals.css'
import { Providers } from './providers'
import { ThemeSwitcher } from '@/components/themeSwitcher'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PRL Blog',
  description: 'Generated by Daniel Prendas'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-slate-200 dark:bg-slate-950 text-slate-950 dark:text-slate-300`}>
        <Providers>
          <ThemeSwitcher />
          {children}
        </Providers>
      </body>
    </html>
  )
}
